# description
name: "job"
description: ""
keywords: ""
author: "Leszek Pietrzak"

# address settings
baseurl: "http://job.magicznyleszek.xyz"
rootSiteUrl: "http://magicznyleszek.xyz"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw

# excludes
exclude:
    # disabled src, as it breaks --watch (see includes_dir below)
    # - src
    - node_modules
    - LICENSE
    - README.md
    - package.json

# pull includes from other directory
includes_dir: src
